version: "3"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis